#!/bin/bash
#########################################################################
#									#
# Script : rtorrent_postprocess						#
# Description : Script de PostProcess pour rtorrent utilisant filebot		#
#									#
# Auteur : GorMsoN                                                      #
#                                                                       #
#########################################################################

#Chemin du torrent
TORRENT_PATH=$1
#Nom du Torrent
TORRENT_NAME=$2
#Label affecté au torrent permettant de gérer les conditions
TORRENT_LABEL=$3


if [ $TORRENT_LABEL = "tv_vo" ]
then
 
sh /home/"$USER"/.filebot/filebot.sh --lang en -script fn:amc --output "/home/"$USER"/termines" --log-file "/home/"$USER"/.session/amc.log" --action hardlink --conflict override -non-strict --def plex=localhost:18p4tz6EYH5Vo2Jb3fwf unsorted=y "seriesFormat={output}/tv_vo/{n}/{n} - {s00e00}" "movieFormat={output}/movie_vrac/{n} ({y})" "ut_dir=$TORRENT_PATH" "ut_kind=multi" "ut_title=$TORRENT_NAME" "ut_label=tv" &

elif [ $TORRENT_LABEL = "tv_vf" ]
then

sh /home/"$USER"/.filebot/filebot.sh --lang fr -script fn:amc --output "/home/"$USER"/termines" --log-file "/home/"$USER"/.session/amc.log" --action hardlink --conflict override -non-strict --def plex=localhost:18p4tz6EYH5Vo2Jb3fwf unsorted=y "seriesFormat={output}/tv_vf/{n}/{n} - {s00e00}" "movieFormat={output}/movie_vrac/{n} ({y})" "ut_dir=$TORRENT_PATH" "ut_kind=multi" "ut_title=$TORRENT_NAME" "ut_label=tv" &

elif [ $TORRENT_LABEL = "movie_hd" ]
then

sh /home/"$USER"/.filebot/filebot.sh --lang fr -script fn:amc --output "/home/"$USER"/termines" --log-file "/home/"$USER"/.session/amc.log" --action hardlink --conflict override -non-strict --def plex=localhost:18p4tz6EYH5Vo2Jb3fwf unsorted=y "seriesFormat={output}/tv_vo/{n}/{n} - {s00e00}" "movieFormat={output}/movie_hd/{n} ({y})" "ut_dir=$TORRENT_PATH" "ut_kind=multi" "ut_title=$TORRENT_NAME" "ut_label=movie" &

elif [ $TORRENT_LABEL = "movie_vrac" ]
then

sh /home/"$USER"/.filebot/filebot.sh --lang fr -script fn:amc --output "/home/"$USER"/termines" --log-file "/home/"$USER"/.session/amc.log" --action hardlink --conflict override -non-strict --def plex=localhost:18p4tz6EYH5Vo2Jb3fwf unsorted=y "seriesFormat={output}/tv_vo/{n}/{n} - {s00e00}" "movieFormat={output}/movie_vrac/{n} ({y})" "ut_dir=$TORRENT_PATH" "ut_kind=multi" "ut_title=$TORRENT_NAME" "ut_label=movie" &

elif [ $TORRENT_LABEL = "kids" ]
then

sh /home/"$USER"/.filebot/filebot.sh --lang fr -script fn:amc --output "/home/"$USER"/termines" --log-file "/home/"$USER"/.session/amc.log" --action hardlink --conflict override -non-strict --def plex=localhost:18p4tz6EYH5Vo2Jb3fwf unsorted=y "seriesFormat={output}/tv/{n}/{n} - {s00e00}" "movieFormat={output}/movie_kids/{n} ({y})" "ut_dir=$TORRENT_PATH" "ut_kind=multi" "ut_title=$TORRENT_NAME" "ut_label=movie" &

fi
